using NTwain.Data;
using NTwain.Data.Kds;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NTwain.Caps;

partial class KdsCaps
{

    CapWriter<TWBS>? _ICAP_BACKGROUNDADJUSTMODE;
    public CapWriter<TWBS> ICAP_BACKGROUNDADJUSTMODE =>
        _ICAP_BACKGROUNDADJUSTMODE ??= new(_twain, (CAP)KDS_CAP.ICAP_BACKGROUNDADJUSTMODE, 2);



    CapWriter<TWBA>? _ICAP_BACKGROUNDADJUSTAPPLYTO;
    public CapWriter<TWBA> ICAP_BACKGROUNDADJUSTAPPLYTO =>
        _ICAP_BACKGROUNDADJUSTAPPLYTO ??= new(_twain, (CAP)KDS_CAP.ICAP_BACKGROUNDADJUSTAPPLYTO, 2);



    CapWriter<int>? _ICAP_BACKGROUNDADJUSTAGGRESSIVENESS;
    public CapWriter<int> ICAP_BACKGROUNDADJUSTAGGRESSIVENESS =>
        _ICAP_BACKGROUNDADJUSTAGGRESSIVENESS ??= new(_twain, (CAP)KDS_CAP.ICAP_BACKGROUNDADJUSTAGGRESSIVENESS, 2);



    CapWriter<TWIE>? _ICAP_IMAGEEDGEFILL;
    public CapWriter<TWIE> ICAP_IMAGEEDGEFILL =>
        _ICAP_IMAGEEDGEFILL ??= new(_twain, (CAP)KDS_CAP.ICAP_IMAGEEDGEFILL, 2);


    CapWriter<TWCR>? _ICAP_CROPPINGMODE;
    public CapWriter<TWCR> ICAP_CROPPINGMODE =>
        _ICAP_CROPPINGMODE ??= new(_twain, (CAP)KDS_CAP.ICAP_CROPPINGMODE, 2);


    CapWriter<TW_FIX32>? _ICAP_IMAGEEDGELEFT;
    public CapWriter<TW_FIX32> ICAP_IMAGEEDGELEFT =>
        _ICAP_IMAGEEDGELEFT ??= new(_twain, (CAP)KDS_CAP.ICAP_IMAGEEDGELEFT, 2);

    CapWriter<TW_FIX32>? _ICAP_IMAGEEDGERIGHT;
    public CapWriter<TW_FIX32> ICAP_IMAGEEDGERIGHT =>
        _ICAP_IMAGEEDGERIGHT ??= new(_twain, (CAP)KDS_CAP.ICAP_IMAGEEDGERIGHT, 2);


    CapWriter<TW_FIX32>? _ICAP_IMAGEEDGETOP;
    public CapWriter<TW_FIX32> ICAP_IMAGEEDGETOP =>
        _ICAP_IMAGEEDGETOP ??= new(_twain, (CAP)KDS_CAP.ICAP_IMAGEEDGETOP, 2);

    CapWriter<TW_FIX32>? _ICAP_IMAGEEDGEBOTTOM;
    public CapWriter<TW_FIX32> ICAP_IMAGEEDGEBOTTOM =>
        _ICAP_IMAGEEDGEBOTTOM ??= new(_twain, (CAP)KDS_CAP.ICAP_IMAGEEDGEBOTTOM, 2);

    CapWriter<TW_BOOL>? _ICAP_IMAGEEDGEFILLALLSIDES;
    public CapWriter<TW_BOOL> ICAP_IMAGEEDGEFILLALLSIDES =>
        _ICAP_IMAGEEDGEFILLALLSIDES ??= new(_twain, (CAP)KDS_CAP.ICAP_IMAGEEDGEFILLALLSIDES, 2);

    CapWriter<TW_BOOL>? _ICAP_HOLEFILLENABLED;
    public CapWriter<TW_BOOL> ICAP_HOLEFILLENABLED =>
        _ICAP_HOLEFILLENABLED ??= new(_twain, (CAP)KDS_CAP.ICAP_HOLEFILLENABLED, 2);


    CapWriter<TW_BOOL>? _ICAP_STREAKREMOVALENABLED;
    public CapWriter<TW_BOOL> ICAP_STREAKREMOVALENABLED =>
        _ICAP_STREAKREMOVALENABLED ??= new(_twain, (CAP)KDS_CAP.ICAP_STREAKREMOVALENABLED, 2);

    CapWriter<int>? _ICAP_STREAKREMOVALAGGRESSIVENESS;
    public CapWriter<int> ICAP_STREAKREMOVALAGGRESSIVENESS =>
        _ICAP_STREAKREMOVALAGGRESSIVENESS ??= new(_twain, (CAP)KDS_CAP.ICAP_STREAKREMOVALAGGRESSIVENESS, 2);


}
